title: "Hawthorne Field Guide"
baseurl: "/FieldGuide"
markdown: kramdown
theme: null

kramdown:
  parse_block_html: true

collections:
  monsters:
    output: true
    permalink: /monsters/:name/

# Disable default GitHub Pages theme
theme: null

defaults:
  - scope:
      path: ""
      type: "monsters"
    values:
      layout: "statblock"

exclude:
  - ".DS_Store"
  - "Thumbs.db"
  - "node_modules"
