title: "D&D Monster Compendium"
baseurl: "/FieldGuide"
markdown: kramdown
kramdown:
  parse_block_html: true

collections:
  monsters:
    output: true
    permalink: /monsters/:name/

# ADD THIS LINE TO PREVENT THE GITHUB DEFAULT THEME FROM INTERFERING
theme: null

defaults:
  - scope:
      path: ""
      type: "monsters"
    values:
      layout: "statblock"

# ADD THIS SECTION TO PREVENT BUILD FAILURES FROM JUNK FILES
exclude:
  - ".DS_Store"
  - "Thumbs.db"
  - "node_modules"
