title: "D&D Monster Compendium"
markdown: kramdown
kramdown:
  parse_block_html: true

# Jekyll settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  monsters:
    output: true
    permalink: /monsters/:name/

defaults:
  - scope:
      path: ""
      type: "monsters"
    values:
      layout: "statblock"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - README.md
