title: "D&D Monster Compendium"
baseurl: "/FieldGuide"
markdown: kramdown
kramdown:
  parse_block_html: true

collections:
  monsters:
    output: true
    permalink: /monsters/:name/

# CRITICAL FIX: Stops the conflicting default theme
theme: null

defaults:
  - scope:
      path: ""
      type: "monsters"
    values:
      layout: "statblock"

exclude:
  - ".DS_Store"
  - "Thumbs.db"
  - "node_modules"
